# Generated by Django 4.1 on 2022-08-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cuenta', models.IntegerField()),
                ('contrasena', models.CharField(max_length=4)),
                ('documento', models.CharField(max_length=50)),
                ('tipo_doc', models.IntegerField()),
                ('direccion', models.IntegerField()),
                ('correo', models.CharField(max_length=320)),
            ],
        ),
        migrations.CreateModel(
            name='cuenta',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('convencional', models.CharField(max_length=100)),
                ('saldo_principal', models.IntegerField()),
                ('QR', models.CharField(max_length=100)),
            ],
        ),
    ]
