# Generated by Django 4.1 on 2022-09-04 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(blank=True, max_length=50, null=True)),
                ('barrio', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(max_length=50)),
                ('casa', models.CharField(blank=True, max_length=50, null=True)),
                ('departamento', models.CharField(max_length=50)),
                ('apartamento', models.CharField(blank=True, max_length=50, null=True)),
                ('vereda', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='estado_cuenta',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_doc',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_doc',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cuenta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cuenta'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='QR',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='convencional',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='saldo_principal',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='documento',
            fields=[
                ('id_doc', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=100, unique=True)),
                ('expedicion', models.DateField()),
                ('nombre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.tipo_doc')),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='estado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='usuarios.estado_cuenta'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.direccion'),
        ),
    ]
