# Generated by Django 4.1 on 2022-09-04 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_cuenta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.estado_cuenta'),
        ),
    ]
