# Generated by Django 4.1 on 2022-09-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_cuenta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='celular',
            field=models.CharField(default='0123456789', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
