# Generated by Django 4.1 on 2022-09-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_cliente_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nacimiento',
            #
            field=models.DateField(default='2022-01-01'),
            preserve_default=False,
        ),
    ]
