# Generated by Django 4.1 on 2022-09-04 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_cliente_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nacimiento',
        ),
    ]
