# Generated by Django 4.1 on 2022-09-04 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_cliente_nacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nacimiento',
            new_name='fecha_nacimiento',
        ),
    ]
