# Generated by Django 4.1 on 2022-09-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_rename_nacimiento_cliente_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_nac',
            field=models.DateField(default='2022-01-01'),
            preserve_default=False,
        ),
    ]
