# Generated by Django 4.1 on 2022-09-04 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_remove_cliente_fecha_nacimiento_cliente_fecha_nac'),
    ]

    operations = [
        migrations.CreateModel(
            name='apartamento',
            fields=[
                ('id_apartamento', models.AutoField(primary_key=True, serialize=False)),
                ('conjunto', models.CharField(max_length=200)),
                ('bloque', models.CharField(blank=True, max_length=200, null=True)),
                ('num_apar', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='direccion',
            name='apartamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.apartamento'),
        ),
    ]
