# Generated by Django 4.1 on 2022-09-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_apartamento_alter_direccion_apartamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_nac',
        ),
        migrations.AddField(
            model_name='cliente',
            name='nacimiento',
            field=models.DateField(default='2022-01-01'),
        ),
    ]
