# Generated by Django 4.1 on 2022-09-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_remove_cliente_fecha_nac_cliente_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='carrera',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
