# Generated by Django 4.1 on 2022-09-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_direccion_carrera_alter_direccion_calle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nacimiento',
            field=models.DateField(),
        ),
    ]
