# Generated by Django 4.1 on 2022-09-05 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_alter_cliente_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='bolsillo',
            fields=[
                ('id_bol', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=10)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='envio',
            fields=[
                ('id_envio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('IP_envia', models.CharField(max_length=128)),
                ('monto', models.IntegerField()),
                ('bol_recibe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.bolsillo')),
                ('recibe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.cuenta')),
            ],
        ),
    ]
