# Generated by Django 4.1 on 2022-09-05 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_bolsillo_envio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='QR',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='saldo_principal',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='bol_recibe',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='recibe',
        ),
        migrations.AddField(
            model_name='bolsillo',
            name='QR',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bolsillo',
            name='principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='contrasena',
            field=models.CharField(default='1234', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='envio',
            name='envia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.bolsillo'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='recibe',
            fields=[
                ('id_envio', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='usuarios.envio')),
                ('recibe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.bolsillo')),
            ],
        ),
    ]
