# Generated by Django 4.1 on 2022-09-06 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_remove_cliente_contrasena_remove_cuenta_qr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='convencional',
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='estado',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.estado_cuenta'),
        ),
    ]
