# Generated by Django 4.1 on 2022-09-06 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_remove_cuenta_convencional_alter_cuenta_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='apartamento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tipo_doc'),
        ),
        migrations.DeleteModel(
            name='apartamento',
        ),
        migrations.DeleteModel(
            name='direccion',
        ),
    ]
