# Generated by Django 4.1 on 2022-09-06 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_remove_direccion_apartamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='recibe',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_recibe', to='usuarios.bolsillo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='envio',
            name='envia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_envia', to='usuarios.bolsillo'),
        ),
        migrations.DeleteModel(
            name='recibe',
        ),
    ]
