# Generated by Django 4.1 on 2022-09-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_envio_recibe_alter_envio_envia_delete_recibe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolsillo',
            name='principal',
        ),
        migrations.AlterField(
            model_name='bolsillo',
            name='QR',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bolsillo',
            name='monto',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='bolsillo',
            name='nombre',
            field=models.CharField(blank=True, default='principal', max_length=10),
        ),
    ]
