# Generated by Django 4.1 on 2022-09-10 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_remove_bolsillo_principal_alter_bolsillo_qr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envio',
            old_name='envia',
            new_name='envia_id',
        ),
        migrations.RenameField(
            model_name='envio',
            old_name='recibe',
            new_name='recibe_id',
        ),
    ]
