# Generated by Django 4.1 on 2022-09-14 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_rename_envia_envio_envia_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='IP_envia',
        ),
    ]
