# Generated by Django 4.1 on 2022-09-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_remove_envio_ip_envia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='colchon',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
